### PR TITLE
CI Upgrade

### PR DESCRIPTION
**Pull request by DJStompZone**
Added CodeQL analysis for Node 16, 18, and 20 on a wide range of Windows, MacOS, and Linux environments, upgraded previous ci workflow to use latest versions of leveraged github actions

### CODE REVIEW

**Comment by DJStompZone** [comment]
Workflow demonstration:
https://github.com/DJStompZone/bedrock-portal/actions/runs/6064583875

[CodeQL](https://github.com/DJStompZone/bedrock-portal/actions/workflows/codeql.yml)

**Comment by LucienHH** [comment]
Hey DJ, thanks for the PR. What's exactly is this for, I assume code analysis but when it does a scan what is it looking for?

**Comment by LucienHH** [comment]
Well that's a convenient reply, don't see the harm in this.

**Review by LucienHH — APPROVED** [review]

**Comment by LucienHH** [comment]
Thanks

**Pull request merged**
